[tool.poetry]
name = "xclone"
version = "0.3.6"
description = "xclone - Inference of clonal Copy Number Alterations in single cells"
authors = ["Rongting Huang<rthuang@connect.hku.hk>"]
readme = "README.rst"

[tool.poetry.dependencies]
python = "^3.9"
numpy = "^1.26.4"
scipy = "^1.13.1"
matplotlib = "^3.9.0"
anndata = "^0.10.7"
statsmodels = "^0.14.2"
scanpy = "^1.10.1"
h5py = "^3.11.0"
palettable = "^3.3.3"
requests = "^2.32.3"
importlib-metadata = "^7.1.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
